config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects do
    resources :issues, only: [:new, :create]
  end

  resources :issues, except: [:new, :create] do
    resources :comments
  end
  # get '/projects/:project_id/issues', to: 'issues#new', as: 'new_issue'
  # post '/projects/:project_id/issues', to: 'issues#create', as: 'create_issue'

  root 'projects#index'
  get '/user/:id', to: 'users#show', as: 'profile'
  get 'owner/:project_id/:id', to: 'projects#make_leader', as: 'leader'
  post '/member/:id', to: 'project_members#create', as: 'member'

  get 'projects/:id/search', to: 'issues#search', as: 'search'
  get 'issues/:id/done', to: 'issues#done', as: 'done_status'
  get 'issues/:id/close', to: 'issues#close_issue', as: 'close_issue'
  get 'projects/:id/close_list', to: 'issues#close_list', as: 'close_list'

  delete 'project_members/:id', to: 'project_members#destroy', as: 'remove'

  mount LetterOpenerWeb::Engine, at: "/letter_opener"

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :issue

  validates :content, length: { in: 1..500 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_issue, only: [:create, :edit, :update]

  def create
    @comment = @issue.comments.build(comment_params)
    @comment.user = current_user
    respond_to do |format|
      if @comment.save
        flash.now[:alert] = 'Commented'
        format.js { render :index }
      else
        flash.now[:alert] = 'Comment cannot be blank'
        format.js { render :index }
      end
    end
  end

  def edit
    @comment = @issue.comments.find(params[:id])
    if current_user == @comment.user
      respond_to do |format|
        flash.now[:alert] = 'Editing a comment'
        format.js { render :edit }
      end
    else
      redirect_to issue_path(@issue), notice: "You can only edit and delete your comments"
    end
  end

  def update
    @comment = @issue.comments.find(params[:id])
      respond_to do |format|
        if @comment.update(comment_params)
          flash.now[:alert] = 'The comment has been edited'
          format.js { render :index }
        else
          flash.now[:alert] = 'Failed to edit comment'
          format.js { render :edit_error }
        end
      end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @issue = @comment.issue
    @project = @issue.project
    if current_user == @comment.user || current_user.id = @project.owner_id
      @comment.destroy
      respond_to do |format|
        flash.now[:alert] = 'Comment deleted'
        format.js { render :index }
      end
    else
      redirect_to issue_path(@issue), notice: "You can only edit and delete your comments"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:issue_id, :content)
  end

  def set_issue
    @issue = Issue.find(params[:issue_id])
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_edit.html.erb
<%= form_with(model: [issue, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %>prohibited this comment from being saved:</h2>
      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field mt-2">
    <%= form.text_area :content, id: "comment_content_#{issue.id}",
        class:"form-control form-control-lg", type:"text-area", col:"4", placeholder:"Write a comment" %>
  </div>
  <div class="text-right mt-2 mb-3">
    <%= form.submit 'Update', class:"btn", style:"background-color: #70adb5;" %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: [issue, comment]) do |form| %>
  <div class="field mt-5">
    <%= link_to current_user.username, profile_path(current_user) %>
    <%= form.text_area :content, class:"form-control form-control-lg", type:"text-area", col:"4", placeholder:"Write a comment" %>
  </div>
  <div class="text-right mt-3">
    <%= form.submit 'Comment', class:"btn", style:"background-color: #70adb5;" %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<% if flash.alert %>
  <div class="alert my-0 alert-success alert-dismissible fade show" role="alert">
    <%= flash.alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% comments.each do |comment| %>
  <div class="container mt-0 mb-2">
    <% if comment.errors.any? %>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <h4><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h4>
        <% comment.errors.full_messages.each do |message| %>
          <p><%= message %></p>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        <% end %>
      </div>
    <% end %>
  </div>

  <% if comment.id.present? %>

    <div id="this_comment_<%= comment.id %>">
      <p class="mt-3 mb-0">
        <%= link_to comment.user.username, profile_path(comment.user) %>
      </p>
      <p class="border border-info rounded my-0 p-2">
        <%= comment.content %>
      </p>
      <% if current_user == comment.user %>
        <p class="mt-0 text-right">
          <%= link_to 'Edit', edit_issue_comment_path(issue, comment), remote: true %> |
          <%= link_to 'Delete', issue_comment_path(comment.issue_id, comment.id), method: :delete, remote: true,
                                          data: { confirm: "Do you really want to delete this?"} %>
        </p>
      <% elsif current_user.id == @project.owner_id %>
        <p class="mt-0 text-right">
          <%= link_to 'Delete', issue_comment_path(comment.issue_id, comment.id), method: :delete, remote: true,
                                          data: { confirm: "Do you really want to delete this?"} %>
        </p>
      <% end %>
    </div>
    <p class="comment-content" id="this_comment_<%= comment.id %>"></p>
  <% end %>
<% end %>

app/views/comments/edit.js.erb
$("#this_comment_<%= @comment.id %>").hide();
$("#this_comment_<%= @comment.id %>").replaceWith("<%= j render 'comments/edit', issue: @issue, comment: @comment %>");

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.issue.comments, issue: @comment.issue }) %>")
$("textarea").val('')