config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects do
    resources :issues, only: [:new, :create]
  end

  resources :issues, except: [:new, :create] do
    resources :comments
  end
  # get '/projects/:project_id/issues', to: 'issues#new', as: 'new_issue'
  # post '/projects/:project_id/issues', to: 'issues#create', as: 'create_issue'

  root 'projects#index'
  get '/user/:id', to: 'users#show', as: 'profile'
  get 'owner/:project_id/:id', to: 'projects#make_leader', as: 'leader'
  post '/member/:id', to: 'project_members#create', as: 'member'

  get 'projects/:id/search', to: 'issues#search', as: 'search'
  get 'issues/:id/done', to: 'issues#done', as: 'done_status'
  get 'issues/:id/close', to: 'issues#close_issue', as: 'close_issue'
  get 'projects/:id/close_list', to: 'issues#close_list', as: 'close_list'

  delete 'project_members/:id', to: 'project_members#destroy', as: 'remove'

  mount LetterOpenerWeb::Engine, at: "/letter_opener"

end

app/models/issue.rb
class Issue < ApplicationRecord
  belongs_to :user
  belongs_to :project
  has_many :comments, dependent: :destroy

  validates :summary, length: { in: 6..60 }
  validates :detail, length: { in: 6..3000 }
  validates :issue_type, presence: true
  validates :priority, presence: true
  validates :assigned_person, presence: true
  validates_datetime :due_date, allow_blank: true, on_or_after: :today
  validates :status, presence: true

  mount_uploader :image, ImageUploader

  enum issue_type: { Other: 0, Feature: 1, Bug: 2, Error: 3, Fatal: 4 }
  enum priority: { Low: 0, Medium: 1, High: 2, Urgent: 3 }
  enum status: { Init: 0, Assigned: 1, Doing: 2, Done: 3 }

  scope :search, ->(project, summary, type) {
    @project = project
    @pmembers = ProjectMember.where(project_id: @project)
    @summary_param = summary.to_s.downcase
    @type_param = type

    if @summary_param.present? && @type_param.blank?
      @project.issues.where("lower(summary) LIKE ?", "%#{@summary_param}%")

    elsif @type_param.present? && @summary_param.blank?
      @project.issues.where(issue_type: @type_param)

    elsif @summary_param.present? && @type_param.present?
      @filters = @project.issues.where(issue_type: @type_param)
      @filters.where("lower(summary) LIKE ?", "%#{@summary_param}%")
    end
  }

end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController

  def close_list
    @project = Project.find(params[:id])
    @issues = @project.issues.where(close_issue: true)
    @closed_issues = @issues.all.order(created_at: :desc).paginate(page: params[:page], per_page: 15)
  end

  def new
    @issue = Issue.new
    @project = Project.find(params[:project_id])
    @member_names = []
    @project.members.each do |member|
      @member_names << member.username
    end
  end

  def edit
    @issue = set_issue
    if @issue.close_issue
      redirect_to @issue, notice: "This issue has been closed"
    else
      @project = Project.find(@issue.project_id)
      @submitted = User.find_by(username: @issue.assigned_person)
      @member_names = []
      @project.members.each do |member|
        @member_names << member.username
      end
    end
  end

  def create
    @project = Project.find(params[:project_id])
    @member_names = []
    @project.members.each do |member|
      @member_names << member.username
    end
    @issue = @project.issues.build(issue_params)
    @issue.user_id = current_user.id
    if @issue.save
      flash[:notice] = "Issue Created"
      redirect_to @issue
    else
      render 'new'
    end

  end

  def search
    @project = Project.find(params[:id])
    if params[:summary].present? || params[:type].present?
      @results = Issue.search(@project, params[:summary], params[:type])
    else
      redirect_to project_path, notice: "Please provide the search keyword or select the issue type"
    end
  end

  def done
    @issue = set_issue
    @issue.status = 'Done'
    @issue.save
    redirect_to issue_path(@issue), notice: "Set Issue Status Done"
  end

  def close_issue
    @issue = set_issue
    @project = Project.find(@issue.project_id)
    if current_user.id == @issue.user_id || current_user.id == @project.owner_id
      if @issue.status == 'Done'
        @issue.toggle!(:close_issue)
        @issue.save
        redirect_to issue_path(@issue), notice: "Close Issue Successfully"
      else
        redirect_to issue_path(@issue), notice: "Status must be done to close issue"
      end
    else
      redirect_to issue_path(@issue), notice: "Only leader or submitted person can close the issue"
    end
  end

  def update
    @issue = set_issue
    if @issue.update(issue_params)
      flash[:notice] = "Edited Successfully"
      redirect_to @issue
    else
      redirect_to edit_issue_path, alert: @issue.errors.full_messages
    end
  end

  def show
    @issue = set_issue
    @project = Project.find(@issue.project_id)
    @submitted_person = User.find(@issue.user_id)
    @assigned_person = User.find_by(username: @issue.assigned_person)
    @comments = @issue.comments
    @comment = @issue.comments.build
  end

  private

  def set_issue
    @issue = Issue.find(params[:id])
  end

  def issue_params
    params.require(:issue).permit(:user_id, :project_id, :summary,
       :detail, :issue_type, :priority, :assigned_person, :status,
       :due_date, :image, :image_cache)
  end

end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/close_list.html.erb
<% if @closed_issues.present? %>
  <h2 class="text-center mb-3">Closed Issues List</h2>
  <table class="table">
    <div class="row">
      <h5 class="col">
        <span class="text-right">Project Name: </span>
        <%= link_to @project.name, project_path(@project), class:"text-right" %>
      </h5>
      <h5 class="col"><%= will_paginate @closed_issues, class:"text-center" %></h5>
    </div>
    <thead style="background-color: #70adb5;">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Issues</th>
        <th scope="col">Type</th>
        <th scope="col">Priority</th>
        <th scope="col">Assigned Person</th>
        <th scope="col">Submitted Person</th>
        <th scope="col">Status</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @closed_issues.each.with_index(1) do |issue, index| %>
        <% assigned_person = User.find_by(username: issue.assigned_person) %>
        <tr>
          <td>
            <%= index %>
          </td>
          <td>
            <%= issue.summary %>
          </td>
          <td>
            <%= issue.issue_type %>
          </td>
          <td>
            <%= issue.priority %>
          </td>
          <td>
            <%= link_to assigned_person.username, profile_path(assigned_person.id) %>
            <% if assigned_person.id == @project.owner_id %>
              (Leader)
            <% else %>
              <% if project_member = ProjectMember.find_by(user_id: assigned_person.id, project_id: @project) %>
                (<%= project_member.role %>)
              <% else %>
                (Remove)
              <% end %>
            <% end %>
          </td>
          <td>
            <%= link_to issue.user.username, profile_path(issue.user) %>
            <% if issue.user.id == @project.owner_id %>
              (Leader)
            <% else %>
              <% if project_member = ProjectMember.find_by(user_id: issue.user, project_id: @project) %>
                (<%= project_member.role %>)
              <% else %>
                (Remove)
              <% end %>
            <% end %>
          </td>
          <td>
            <%= issue.status %>
          </td>
          <td>
            <%= link_to 'Detail', issue_path(issue), class:"btn btn-sm mx-0 btn-outline-info" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="text-center mb-2" >
    <%= link_to 'Add New Issue', new_project_issue_path(@project), class:"btn mt-2 mb-5", style:"background-color: #70adb5;" %>
  </div>
<% else %>
  <h2 class="text-center my-3">Currently, there are no closed issues in this project.</h2>
  <h4 class="text-center"><%= link_to 'Back to project', project_path(@project) %></h4>
<% end %>

app/views/issues/edit.html.erb
<div class="container text-center">

  <%= form_with(model: @issue, local: true) do |form| %>
    <div class="container col-9">
      <div class="card text-center">
        <div class="card-header bg-grey">
          <div class="row">
            <div class="col text-left">
              <strong>Project Name: </strong>
              <%= link_to @project.name, project_path(@project) %>
            </div>
            <div class="col text-center">
              <%= link_to 'Back to Issue', issue_path(@issue) %>
            </div>
            <div class="col text-right">
              <strong>Submitted by: </strong>
              <%= link_to @issue.user.username, profile_path(current_user) %>
            </div>
          </div> <br>
          <div class="row">
            <div class="col text-center">
              <h1>Edit Issue</h1>
            </div>
          </div>
        </div>

        <div class="card-body">
          <p class="card-text text-left">
            <%= form.label :summary %>
            <%= form.text_field :summary, class:"form-control", placeholder:"Enter Issue Summary", autofocus: true %>
          </p>
          <p class="card-text text-left">
            <%= form.label :detail %>
            <%= form.text_area :detail, rows:"4", class:"form-control", placeholder:"Enter Detail Explanation of Issue" %>
          </p>
          <p class="card-text text-left">
            <%= form.label :issue_type %>:
            <%= form.select :issue_type, Issue.issue_types.keys, class: 'form-control' %>
          </p>
          <p class="card-text text-left">
            <%= form.label :priority %>:
            <%= form.select :priority, Issue.priorities.keys, class: 'form-control' %>
          </p>
          <p class="card-text text-left">
            <%= form.label :assigned_person %>:
            <%= form.select :assigned_person, @member_names, class: 'form-control' %>
          </p>
          <p class="card-text text-left">
            <%= form.label :status %>:
            <%= form.select :status, Issue.statuses.keys, class: 'form-control' %>
          </p>
          <p class="card-text text-left">
            <%= form.label :due_date %>:
            <%= form.datetime_field :due_date, class: 'form-control col-4' %>
          </p>

          <p class="card-text text-left">
            <%= form.label :image %>:
            <%= form.file_field :image %>
            <%= form.hidden_field :image_cache %>
          </p>

        </div>

        <div class="card-footer">
          <p>
            <%= form.submit 'Update Issue', class: "btn mt-3 col-3",
              style:"background-color: #70adb5;" %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/issues/new.html.erb
<div class="container text-center">

  <%= form_with(model: [@project, @issue], local: true) do |form| %>
    <div class="container mb-2">
      <% if @issue.errors.any? %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>
          <% @issue.errors.full_messages.each do |message| %>
            <p><%= message %></p>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          <% end %>
        </div>
      <% end %>
    </div>

    <div class="container col-9">
      <div class="card text-center">
        <div class="card-header bg-grey">
          <div class="row">
            <div class="col text-left">
              <strong>Project Name: </strong>
              <%= link_to @project.name, project_path(@project) %>
            </div>
            <div class="col text-right">
              <strong>Submitted by: </strong>
              <%= link_to current_user.username, profile_path(current_user) %>
            </div>
          </div> <br>
          <div class="row">
            <div class="col text-center">
              <h1>New Issue</h1>
            </div>
          </div>
        </div>

        <div class="card-body">
          <p class="card-text text-left">
            <%= form.label :summary %>
            <%= form.text_field :summary, class:"form-control", placeholder:"Enter Issue Summary", autofocus: true %>
          </p>
          <p class="card-text text-left">
            <%= form.label :detail %>
            <%= form.text_area :detail, rows:"4", class:"form-control", placeholder:"Enter Detail Explanation of Issue" %>
          </p>
          <p class="card-text text-left">
            <%= form.label :issue_type %>:
            <%= form.select :issue_type, Issue.issue_types.keys, class: 'form-control' %>
          </p>
          <p class="card-text text-left">
            <%= form.label :priority %>:
            <%= form.select :priority, Issue.priorities.keys, class: 'form-control' %>
          </p>
          <p class="card-text text-left">
            <%= form.label :assigned_person %>:
            <%= form.select :assigned_person, @member_names, class: 'form-control' %>
          </p>
          <p class="card-text text-left">
            <%= form.label :status %>:
            <%= form.select :status, Issue.statuses.keys, class: 'form-control' %>
          </p>
          <p class="card-text text-left">
            <%= form.label :due_date %>:
            <%= form.datetime_field :due_date, class: 'form-control col-4' %>
          </p>
          <p class="card-text text-left">
            <%= form.label :image %>:
            <%= form.file_field :image %>
          </p>

        </div>

        <div class="card-footer">
          <p>
            <%= form.submit 'Create Issue', class: "btn mt-3 col-3",
              style:"background-color: #70adb5;" %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/issues/search.html.erb
<% if @results.present? %>
  <table class="table">
    <h2 class="text-center mb-4">Search Results</h2>
    <h5>
      Project Name: <%= link_to @project.name , project_path(@project) %>
    </h5>
    <thead style="background-color: #70adb5;">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Issues</th>
        <th scope="col">Type</th>
        <th scope="col">Priority</th>
        <th scope="col">Assigned Person</th>
        <th scope="col">Submitted Person</th>
        <th scope="col">Status</th>
        <th scope="col">Close</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @results.each.with_index(1) do |issue, index| %>
        <% assigned_person = User.find_by(username: issue.assigned_person) %>
        <tr>
          <td>
            <%= index %>
          </td>
          <td>
            <%= issue.summary %>
          </td>
          <td>
            <%= issue.issue_type %>
          </td>
          <td>
            <%= issue.priority %>
          </td>
          <td>
            <%= link_to assigned_person.username, profile_path(assigned_person.id) %>
            <% if assigned_person.id == @project.owner_id %>
              (Leader)
            <% else %>
              <% project_member = ProjectMember.find_by(user_id: assigned_person.id, project_id: @project) %>
              (<%= project_member.role %>)
            <% end %>
          </td>
          <td>
            <%= link_to issue.user.username, profile_path(issue.user) %>
            <% if issue.user.id == @project.owner_id %>
              (Leader)
            <% else %>
              <% project_member = ProjectMember.find_by(user_id: issue.user, project_id: @project) %>
              (<%= project_member.role %>)
            <% end %>
          </td>
          <td>
            <%= issue.status %>
          </td>
          <td>
            <% if issue.close_issue %>
              <button type="button" class="btn btn-secondary btn-sm" disabled>
                Closed
              </button>
            <% end %>
          </td>
          <td>
            <%= link_to 'Detail', issue_path(issue), class:"btn btn-sm mx-0 btn-outline-info" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h2 class="text-center">There is no issue matched by the search keyword</h2>
  <h4 class="text-center"><%= link_to 'Back to project', project_path(@project) %></h4>
<% end %>

app/views/issues/show.html.erb
<div class="container">

<% if @issue.close_issue %>
  <div class="container mb-2">
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <p>This issue is for record only.</p>
      <p>This issue does not need to involve in project activities</p>
      <p>Because it is resolved successfully and hence it is closed by submitted person.</p>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      </div>
  </div>
<% end %>

<div class="row mb-4">
  <div class="col">
    <h5>
      Project Name: <%= link_to @project.name , project_path(@project) %>
    </h5>
  </div>
  <div class="col text-right">
    <h5>
      Submitted by: <%= link_to @submitted_person.username , profile_path(@submitted_person) %>
    </h5>
  </div>
</div>

<div class="row">
  <div class="col" >
    <p class="issue-detail-text">
      <strong>Summary: </strong><%= @issue.summary %>
    </p>
    <p class="issue-detail-text">
      <strong>Detail: </strong><%= @issue.detail %>
    </p>
    <p class="issue-detail-text">
      <strong>Type: </strong><%= @issue.issue_type %>
    </p>
    <p class="issue-detail-text">
      <strong>Priority: </strong><%= @issue.priority %>
    </p>
    <p class="issue-detail-text"><strong>Assigned person: </strong>
      <%= link_to @assigned_person.username, profile_path(@assigned_person) %>
    </p>
    <p class="issue-detail-text">
      <strong>Status: </strong><%= @issue.status %>
    </p>
    <% if @issue.due_date.present? %>
      <p class="issue-detail-text"><strong>Due Date: </strong><%= @issue.due_date.to_s(:long) %></p>
    <% end %>
    <p class="issue-detail-text">
      <strong>Action: </strong>
      <% if @issue.close_issue %>
        Closed
      <% else %>
        <%= link_to 'Edit Issue', edit_issue_path(@issue) %>
      <% end %>
    </p>

    <% if @issue.image? %>
      <p class="issue-detail-text">
        <strong>Screenshot: </strong>
      </p>
    <% end %>

    <p class="issue-detail-text">
      <%= image_tag(@issue.image.url, size: "500x300") if @issue.image? %>
    </p>

    <% if current_user.id == @issue.user_id || current_user.id == @project.owner_id %>
      <% if !@issue.close_issue %>
        <p class="btn btn-outline-success py-2 px-3" >
          <%= link_to 'Done', done_status_path(@issue) %>
        </p>
        <p class="btn btn-outline-success py-2 px-3" >
          <%= link_to 'Close Issue', close_issue_path(@issue) %>
        </p>
      <% end %>
    <% end %>
  </div>
  <div class="col">
    <div class="issue-detail-text mb-0">
      <strong>Comments</strong>
    </div>
    <div id="comments_area">
      <%= render partial: 'comments/index', locals: { comments: @comments, issue: @issue } %>
    </div>
    <p>
      <%= render partial: 'comments/form', locals: { comment: @comment, issue: @issue } %>
    </p>
  </div>
</div>


</div>