config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects do
    resources :issues, only: [:new, :create]
  end

  resources :issues, except: [:new, :create] do
    resources :comments
  end
  # get '/projects/:project_id/issues', to: 'issues#new', as: 'new_issue'
  # post '/projects/:project_id/issues', to: 'issues#create', as: 'create_issue'

  root 'projects#index'
  get '/user/:id', to: 'users#show', as: 'profile'
  get 'owner/:project_id/:id', to: 'projects#make_leader', as: 'leader'
  post '/member/:id', to: 'project_members#create', as: 'member'

  get 'projects/:id/search', to: 'issues#search', as: 'search'
  get 'issues/:id/done', to: 'issues#done', as: 'done_status'
  get 'issues/:id/close', to: 'issues#close_issue', as: 'close_issue'
  get 'projects/:id/close_list', to: 'issues#close_list', as: 'close_list'

  delete 'project_members/:id', to: 'project_members#destroy', as: 'remove'

  mount LetterOpenerWeb::Engine, at: "/letter_opener"

end

app/models/project.rb
class Project < ApplicationRecord
  has_many :project_members, dependent: :destroy
  has_many :members, through: :project_members, source: :user
  has_many :issues, dependent: :destroy

  validates :name, length: { in: 3..50 }, uniqueness: true
  validates :description, length: { in: 5..300 }

  def invite_member(user, role)
    project_members.create(user: user, role: role)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @projects = current_user.projects.all
  end

  def show
    @sort = params[:sort]
    @leader = User.find(@project.owner_id)
    @pmembers = ProjectMember.where(project_id: @project)
    @issues = @project.issues.where(close_issue: false)
    if @sort
      @active_issues = @issues.all.order(@sort).paginate(page: params[:page], per_page: 5)
    else
      @active_issues = @issues.all.order(created_at: :desc).paginate(page: params[:page], per_page: 5)
    end
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    @project.owner_id = current_user.id
    role = 'Developer'
    if @project.save
      @project.invite_member(current_user, role)
      flash[:notice] = "Project Created"
      redirect_to @project
    else
      render 'new'
    end
  end

  def make_leader
    @user = User.find(params[:id])
    @project = Project.find(params[:project_id])
    @project.owner_id = @user.id
    @project.save
    redirect_to @project
  end

  def update
    if @project.update(project_params)
      flash[:notice] = "Edited Successfully"
      redirect_to @project
    else
      render 'edit'
    end
  end

  def destroy
    if @project.destroy
      flash[:notice] = "Deleted Successfully"
      redirect_to projects_path
    end
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :description)
  end

  def require_same_user
    project = set_project
    if current_user.id != project.owner_id
      flash[:alert] = "You can only edit or delete your own projects"
      redirect_to @project
    end
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_project.html.erb
<div class="container text-center">

  <%= form_with(model: project, local: true) do |form| %>
    <div class="container mb-2">
      <% if project.errors.any? %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>
          <% project.errors.full_messages.each do |message| %>
            <p><%= message %></p>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          <% end %>
        </div>
      <% end %>
    </div>

    <div class="container col-6">
      <div class="card text-center">
        <div class="card-header bg-grey text-center font-weight-bold my-font-size">
          <h1><%= project_header %></h1>
        </div>

        <div class="card-body">
          <p class="card-text text-center">
            <%= form.label :name %>
            <%= form.text_field :name, class:"form-control", placeholder:"Enter Project Name", autofocus: true %>
          </p>
          <p class="card-text text-center">
            <%= form.label :description %>
            <%= form.text_area :description, rows:"4", class:"form-control", placeholder:"Enter Project Description" %>
          </p>
        </div>

        <div class="card-footer">
          <p>
            <%= form.submit "#{name}", class: "btn mt-3 col-3",
              style:"background-color: #70adb5;" %>
          </p>
        </div>
      </div>
    </div>

  <% end %>
  <%= link_to 'Back', projects_path, class:"btn mt-3 col-1",
        style:"background-color: #70adb5;" %>
</div>

app/views/projects/edit.html.erb
<%= render 'project', project_header: 'Editing Project',
        project: @project, name: 'Update Project' %>

app/views/projects/index.html.erb
<% if current_user.projects.present? %>
  <h2 class="text-center mb-4">Your Projects</h2>

  <div class="container col-8">
    <% @projects.each do |project| %>
      <div class="card text-center mb-4 border border-info">
        <div class="card-header" style="background-color: #70adb5;">
          <h4><%= project.name %></h4>
          <%= pluralize(project.issues.count, "issue") %>,
          <%= pluralize(project.members.count, "member") %>
        </div>
        <div class="card-body">
          <p class="card-text"><%= project.description %></p>

          <%= link_to 'Show', project, class:"btn", style:"background-color: #70adb5;" %>
          <% if current_user.id == project.owner_id %>
            <%= link_to 'Edit', edit_project_path(project), class:"btn", style:"background-color: #70adb5;" %>
            <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' },
                class:"btn", style:"background-color: #70adb5;" %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(project.created_at) %> ago,
            edited <%= time_ago_in_words(project.updated_at) %> ago</small>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<div class="text-center" >
  <%= link_to 'New Project', new_project_path, class:"btn mb-3", style:"background-color: #70adb5;" %>
</div>

app/views/projects/new.html.erb
<%= render 'project', project_header: 'New Project',
          project: @project, name: 'Create Project' %>

app/views/projects/show.html.erb
<%# Place Issue field at the top because developers need to check
issues frequently and issues are the main cases for the project %>

<h1 class="text-center"><%= @project.name %></h1>
<p class="text-center mb-4">
  <%= pluralize(@project.issues.count, "issue") %>,
  <%= pluralize(@project.members.count, "member") %>
</p>
<% if @issues.present? %>
  <table class="table table-hover" width="100%">
    <div class="row">
      <h2 class="col-3">Issues List</h2>
      <h5 class="col"><%= will_paginate @active_issues, class:"text-center" %></h5>
      <h5 class="col">
        <%= form_tag(search_path(@project), method: "get") do %>
          <div class="input-group">
            <%= text_field_tag :summary, '', { class: 'form-control',
                  placeholder: "Enter the issue summary"} %>
            <%= select_tag :type,
                  options_for_select(["", "Other", "Feature", "Bug", "Error", "Fatal"]) %>
            <span class="input-group-append">
              <button type="submit" class="btn btn-flat" style="background-color: #70adb5;">
                Search
              </button>
            </span>
          </div>
        <% end %>
      </h5>
    </div>
    <thead style="background-color: #70adb5;">
      <tr>
        <th scope="col">#</th>
        <th scope="col" style="width: 20%">Issues</th>
        <th scope="col" data-toggle="tooltip" title="Sort by Type!">
          <span data-toggle="tooltip" title="ASC">
            <%= link_to '<i class="fa fa-fw fa-sort"></i>'.html_safe, sort: "issue_type asc" %>
          </span>
          Type
          <span data-toggle="tooltip" title="DESC">
            <%= link_to '<i class="fa fa-fw fa-sort"></i>'.html_safe, sort: "issue_type desc" %>
          </span>
        </th>
        <th scope="col" data-toggle="tooltip" title="Sort by Priority!">
          <span data-toggle="tooltip" title="ASC">
            <%= link_to '<i class="fa fa-fw fa-sort"></i>'.html_safe, sort: "priority asc" %>
          </span>
          Priority
          <span data-toggle="tooltip" title="DESC">
            <%= link_to '<i class="fa fa-fw fa-sort"></i>'.html_safe, sort: "priority desc" %>
          </span>
        </th>
        <th scope="col">Assigned person</th>
        <th scope="col" data-toggle="tooltip" title="Sort by Status!">
          <span data-toggle="tooltip" title="ASC">
            <%= link_to '<i class="fa fa-fw fa-sort"></i>'.html_safe, sort: "status asc" %>
          </span>
          Status
          <span data-toggle="tooltip" title="DESC">
            <%= link_to '<i class="fa fa-fw fa-sort"></i>'.html_safe, sort: "status desc" %>
          </span>
        </th>
        <th scope="col" style="width: 20%" data-toggle="tooltip" title="Sort by Due Date!">
          <span data-toggle="tooltip" title="ASC">
            <%= link_to '<i class="fa fa-fw fa-sort"></i>'.html_safe, sort: "due_date asc" %>
          </span>
          Due Date
          <span data-toggle="tooltip" title="DESC">
            <%= link_to '<i class="fa fa-fw fa-sort"></i>'.html_safe, sort: "due_date desc" %>
          </span>
        </th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @active_issues.each.with_index(1) do |issue, index| %>
        <% assigned_person = User.find_by(username: issue.assigned_person) %>
        <tr>
          <td>
            <%= index %>
          </td>
          <td>
            <%= issue.summary %>
          </td>
          <td>
            <%= issue.issue_type %>
          </td>
          <td>
            <%= issue.priority %>
          </td>
          <td>
            <%= link_to assigned_person.username, profile_path(assigned_person.id) %>
            <% if assigned_person.id == @project.owner_id %>
              (Leader)
            <% else %>
              <% if project_member = ProjectMember.find_by(user_id: assigned_person.id, project_id: @project) %>
                (<%= project_member.role %>)
              <% else %>
                (Remove)
              <% end %>
            <% end %>
          </td>
          <td>
            <%= issue.status %>
          </td>
          <td>
            <%= issue.due_date %>
          </td>
          <td>
            <%= link_to 'Detail', issue_path(issue), class:"btn btn-sm mx-0 btn-outline-info" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'View Closed Issues', close_list_path(@project),
        class:"btn btn-sm mx-0 btn-outline-info" %>
  <div class="text-center mb-2" >
    <%= link_to 'Add New Issue', new_project_issue_path(@project),
        class:"btn mt-2 mb-5", style:"background-color: #70adb5;" %>
  </div>
<% else %>
  <h2 class="text-center my-3">Currently, there are no issues in this project. </h2>
  <h3 class="text-center mt-2 mb-5">
    If you want to create one, press <%= link_to 'Add New Issue', new_project_issue_path(@project) %>
  </h3>
<% end %>

<div class="row my-3">
  <div class="col">
    <h2>Showing Project Details</h2>

    <p><strong>Name: </strong><%= @project.name %></p>
    <p><strong>Description: </strong><%= @project.description %></p>
    <%= link_to 'Home', projects_path, class:"btn btn-sm mx-0 btn-outline-info" %>
    <% if current_user.id == @project.owner_id %>
      <%= link_to 'Edit', edit_project_path(@project), class:"btn btn-sm mx-1 btn-outline-info" %>
      <%= link_to 'Delete', project_path(@project),
          class:"btn btn-sm mx-0 btn-outline-info",
          method: :delete, data: { confirm: "Are you sure?" }%>
    <% end %>
  </div>
  <div class="col">
    <h2>Members List</h2>
    <div class="row">
      <h4 class="col-4">Leader: <%= link_to @leader.username, profile_path(@leader) %></h4>
      <div class="col">
        <% if current_user.id == @project.owner_id %>
          <%= form_with model: :project_member, scope: :post, url: member_path(@project.id), local: true do |form| %>
            <div class="input-group">
              <%= text_field_tag :email, '', { class: 'form-control', placeholder: "Enter the email"} %>
              <%= select_tag :role,
              options_for_select(["Developer", "Tester", "User"]), class: 'form-control' %>
              <span class="input-group-append">
                <button type="submit" class="btn btn-flat" style="background-color: #70adb5;">
                  Invite
                </button>
              </span>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <table class="table">
      <thead style="background-color: #70adb5;">
        <tr>
          <th scope="col">Members</th>
          <th scope="col">Role</th>
          <th scope="col" class="text-center" colspan="2">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @pmembers.each do |member| %>
          <% user = User.find(member.user_id) %>
          <% if user.id != @project.owner_id %>
            <tr>
              <td><%= link_to user.username, profile_path(user) %></td>
              <% project_member = ProjectMember.find_by(user_id: user.id, project_id: @project) %>
              <td><%= project_member.role %></td>
              <% if current_user.id == member.project.owner_id %>
                <td class="text-right"><%= link_to 'Make Leader', leader_path(@project, user.id), class:"btn btn-sm mx-0 btn-outline-info" %></td>
                <td class="text-right"><%= link_to 'Remove', remove_path(project_member.id), method: :delete, class: 'btn btn-sm mx-0 btn-outline-danger' %></td>
              <% elsif current_user.id == member.user_id %>
                <td class="text-right"><%= link_to 'Remove', remove_path(project_member.id), method: :delete, class: 'btn btn-sm mx-0 btn-outline-danger' %></td>
              <% else %>
                <td></td>
              <% end %>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>