config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects do
    resources :issues, only: [:new, :create]
  end

  resources :issues, except: [:new, :create] do
    resources :comments
  end
  # get '/projects/:project_id/issues', to: 'issues#new', as: 'new_issue'
  # post '/projects/:project_id/issues', to: 'issues#create', as: 'create_issue'

  root 'projects#index'
  get '/user/:id', to: 'users#show', as: 'profile'
  get 'owner/:project_id/:id', to: 'projects#make_leader', as: 'leader'
  post '/member/:id', to: 'project_members#create', as: 'member'

  get 'projects/:id/search', to: 'issues#search', as: 'search'
  get 'issues/:id/done', to: 'issues#done', as: 'done_status'
  get 'issues/:id/close', to: 'issues#close_issue', as: 'close_issue'
  get 'projects/:id/close_list', to: 'issues#close_list', as: 'close_list'

  delete 'project_members/:id', to: 'project_members#destroy', as: 'remove'

  mount LetterOpenerWeb::Engine, at: "/letter_opener"

end

app/views/layouts/_messages.html.erb
<div class="container mb-2">
  <% flash.each do |name, msg| %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    </div>
  <% end %>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg sticky-top navbar-light mb-5" style="background-color: #70adb5;">
  <%= link_to 'Tracker', projects_path, class:"navbar-brand" %>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <% if user_signed_in? %>
      <ul class="navbar-nav mr-auto">
        <%= link_to 'Inbox', letter_opener_web_path, target: '_blank',
        class: "nav-link" %>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to current_user.username, profile_path(current_user), class:"nav-link" %>
        <li>
        <li class="nav-item">
          <%= link_to 'Edit Account', edit_user_registration_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Log out', destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>
      </ul>
    <% else %>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Log in', new_user_session_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Inbox', letter_opener_web_path, target: '_blank',
          class: "nav-link" %>
        </li>
      </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/nav' %>
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>

  </body>
</html>